### ISSUE TITLE
musste OL mit neuem Profil versehen - Kontaktfenster ohne Name trotz Kontakt

### ISSUE THREAD

**Issue by xantippe** [Kruemelino/FritzBoxTelefon-dingsbums#12]
Hallo Krümmelino,

ich musste in meinem OL 2003 ein neues Profil + neue PST einspielen... Kontakte habe ich deindiziert + indiziert...

bei Anruf geht das Popup-Fenster auch auf mit Nummer -  aber es wird nicht der Name angezeigt trotz vorh. Kontakt :-(

´ne Idee woran das liegen kann?

Gruss und Dank

**Comment by Kruemelino** [comment]
Hast du eine andere Version des Addins installiert?

Momentan bin ich da ratlos. Vielleicht ignieriert das Addin die Neue Datei. Wie hast du sie eingebunden?

Ist in den Einstellungen die Einstellung "Nur den Kontakthauptordner durchsuchen" angeklickt?

**Comment by xantippe** [comment]
ich habe die 3.7.4. inzwischen deinstalliert und die 3.7.12 installiert => bleibt bei dem Effekt :-(

 "Nur den Kontakthauptordner durchsuchen" ist NICHT angeklickt

**Comment by Kruemelino** [comment]
Läuft die Indizierung über die alle Kontakte, auch die die im Anrufmonitor angezeigt werden sollten?

**Comment by xantippe** [comment]
ja - habe mir in den Kontakten die Felder angesehen... nach dem de- und indizieren

**Comment by xantippe** [comment]
also... ich habe:
* die übrigen OL-Profile gelöscht
* FBDB nochmal komplett deinstalliert und die Ordner gelöscht
* neu installiert und eingerichtet
* alle Kontakte nochmal neu de- und dann indiziert
* einen Testkontakt direkt in "Kontakte"
* einen Kontakt über Popup erstellt und indiziert

... es erscheint immer nur die Nummer ohne Name :-((

```
19.03.2015 07:48:21 - Indizierung abgeschlossen: 550 von 550 Kontakten in 11,8686789 s
19.03.2015 07:48:37 - AnrMonAktion: 19.03.15 07:48:37;RING;0;01761234567;341223344;ISDN;
19.03.2015 07:48:38 - AnrMonAktion: 19.03.15 07:48:38;DISCONNECT;0;0;
```

btw: ...wenn Kontakt über Klick auf Popup hat dieser keine Indexfelder - wäre ggf. sinnvoll

**Comment by xantippe** [comment]
wie kann ich die Sache debuggen??

**Comment by Kruemelino** [comment]
Also. Es scheint hier an mehreren Stellen zu hängen. 
Du sagst, dass du die Indizierung durchgeführt hast, Das Log, sagt aus, dass es 550 Einträge waren. Sind die Kontakte danach auch tatsächlich indiziert?

Dann ist nicht klar, ob wirklich die selben Kontakte indiziert wurden, als auch die Kontakte die zur Suche verwendet werden. Es ist aber eher unwahrscheinlich, dass es andere sind. 

Dein letzter Satz "wenn Kontakt über Klick auf Popup hat dieser keine Indexfelder" macht mich stutzig. Du hast im Anrufmonitorfenster den Kontakt geöffnet? Ist es der eigentlich zu suchende Kontakt? Wenn ja: Er hat keine Indizierungsfelder? (Das halte ich für äußerst unwahrscheinlich). 

Kannst du mir mal dein Log und alle Daten schicken? Klick auf Probleme in den Einstellungen,

Danke

Gert

**Comment by xantippe** [comment]
Hallo Gerd,

habe bei den Kontakten nach den eigenen Feldern nachgesehen - die FBDB-Felder sind da...

Du kannst gern per TeamViewer Dir die Sache ansehen oder kommst nochmal rum - "Kaltgetränke und Pizza" wie immer inkl. ;-)

Gruss aus "Hermsdorf"

**Comment by xantippe** [comment]
Logdatei sende ich Dir direkt per E-Mail...

**Comment by Kruemelino** [comment]
Bin in Sachsen. Bin erst Morgen wieder in der Hauptstadt. kann aber gerne draufschauen. Teamviewer installiert sich gerade.

**Comment by xantippe** [comment]
keine Panik - muss mit emeinen Kids gleich essen... können das auch heute Abend, morgen oder in der Woche mal machen...

Dank vorab!

**Comment by Kruemelino** [comment]
Dann eher morgen Abend. Oder mal nächste Woche.
