### ISSUE TITLE
[3.7.12] bei OL 2003: Doppeleintrag bei RWS

### ISSUE THREAD

**Issue by xantippe** [Kruemelino/FritzBoxTelefon-dingsbums#13]
Ich wurde über zwei verschiedene Nummern (MSN) angerufen und FBDB hat über die RWS _zwei_ (identische) Kontakte angelegt...

übrigens: bei der RWS wurde der Name angezeigt => bezüglich #12

**Comment by Kruemelino** [comment]
Prüf das bitte, ob das noch aktuell ist.
