### ISSUE TITLE
[3.8.3] OL belegt 100% einer CPU nach Anruf

### ISSUE THREAD

**Issue by xantippe** [Kruemelino/FritzBoxTelefon-dingsbums#14]
Im meinem OL 2010 geht die CPU-Last auf 25% sprich eine "CPU" wird voll verwendet - beim Schließen von OL raucht es ab; bei Anrufen kann die Tel-Nr nicht oder erst sehr spät aufgelöst werden.

Woran kann das liegen?

**Comment by Kruemelino** [comment]
Versuch mal so viele "Features" zu deaktivieren. Ist die hohe CPU-Auslastung immer, oder erst nach einem eingegangen Telefonat?

**Comment by xantippe** [comment]
erst nach eingegangenem Telefonat - ich versuche gerade herauszubekommen ob es eine Unterscheidung zwischen "kenn ich schon" und "hab ich nich" gibt...

**Comment by Kruemelino** [comment]
Stoppuhr? Anrufmonitor noch eingeblendet?
Hast du die Rückwärtssuche mal ausgeschaltet?

**Comment by xantippe** [comment]
Stopuhr war nicht an - RWS mal abgeschaltet... schaun´wer mal

**Comment by Kruemelino** [comment]
RWS 11880 funktioniert nicht zuverlässig
RWS DasTelefonbuch funktioniert gar nicht mehr

**Comment by Kruemelino** [comment]
Ahh!!!

Da ist der Fehler eine Endlosschleife in der Rückwärtssuche 11880 :-1: 
Auf eine neue Version musst du aber noch warten. Nimm die Rückwärtssuche DasÖrtliche

**Comment by xantippe** [comment]
warum geschlossen - solange kein Bugfix draußen ist, bitte offen lassen/wieder öffnen

**Comment by Kruemelino** [comment]
Das hatte ich doch schon behoben. Es gibt doch schon Version 3.9.10.
Die RWS 11880 funktioniert momentan überhaupt nicht mehr. Das liegt aber nicht an mir sondern an der Seite selbst.

**Comment by xantippe** [comment]
o.k. werde ich testen - bin erst am Freitag wieder in meinem "LAN" inkl. FB...
