### ISSUE TITLE
"Telefone einlesen" lässt Outlook abstürzen

### ISSUE THREAD

**Issue by FUsIon80** [Kruemelino/FritzBoxTelefon-dingsbums#20]
Outlook 365 ProPlus 32bit
Win10 Home 64bit
Fritz.box 7490 (FRITZ!OS:113.06.36-31504 BETA)

Absturz bei "...Backgroundworker..." konnte leider den Text im Debugging nicht schnell genug lesen -.-

**Comment by Kruemelino** [comment]
Besteht das Problem weiterhin? Sorry hab momentan mächtig viel um die Ohren.
Ich versuche mir das noch mal anzuschauen.

**Comment by FUsIon80** [comment]
Leider ja, ich würde gerne weiterhin Ihre Software nutzen, da ich der Meinung bin das diese konkurrenzlos ist  ☺
Wenn ich helfen kann, geben Sie doch bitte Bescheid !!

Von: Gert Michael [mailto:notifications@github.com]
Gesendet: Montag, 23. November 2015 18:42
An: Kruemelino/FritzBoxTelefon-dingsbums <FritzBoxTelefon-dingsbums@noreply.github.com>
Cc: FUsIon80 <funkey-chris@web.de>
Betreff: Re: [FritzBoxTelefon-dingsbums] "Telefone einlesen" lässt Outlook abstürzen (#20)


Besteht das Problem weiterhin? Sorry hab momentan mächtig viel um die Ohren.
Ich versuche mir das noch mal anzuschauen.

**Comment by Kruemelino** [comment]
Was ist die letzte Version, die du verwendet hast? Ist das die 3.9.8?

Geschieht der Absturz direkt am Anfang oder am Ende des Einlesens. Was hast du alles für angeschlossene Telefone?

**Comment by Kruemelino** [comment]
Hast du mal die letzte Version probiert? Darin ist ein neueres Verfahren zum Einlesen enthalten.

**Comment by FUsIon80** [comment]
die neuste funktioniert :D

Von: Gert Michael [mailto:notifications@github.com]
Gesendet: Dienstag, 19. Januar 2016 12:23
An: Kruemelino/FritzBoxTelefon-dingsbums <FritzBoxTelefon-dingsbums@noreply.github.com>
Cc: FUsIon80 <funkey-chris@web.de>
Betreff: Re: [FritzBoxTelefon-dingsbums] "Telefone einlesen" lässt Outlook abstürzen (#20)


Hast du mal die letzte Version probiert? Darin ist ein neueres Verfahren zum Einlesen enthalten.
