### ISSUE TITLE
OL 2013 FBDB 3.10.6: FBDB startet mit OL nicht mit

### ISSUE THREAD

**Issue by zonky2** [Kruemelino/FritzBoxTelefon-dingsbums#29]
Win 7, OL 2013 64bit, FBDB 3.10.6

Ich habe das Problem, dass OL über einige Zeit (Tage) immer mehr RAM beansprucht - teilweise 10 bis 12 GB... daher muss ich ab und an OL neu starten - das FBDB startet aber nicht von allein mit, sondern muss jedes mal über Optionen > Add-Ins > COM-Add-ins mit einem Haken versehen werden :(

**Comment by zonky2** [comment]
eine Idee, wie man das debuggen kann?

**Comment by zonky2** [comment]
Ich habe das hier gefunden https://lexa-it.de/2017/07/outlook-addins-geladen/ - nur finde ich das Addin nicht weder in dem einen noch dem anderen Pfad...?

**Comment by synthetrash** [comment]
Kannst es mal via Group Policy versuchen. Habe es darüber auch für jeden Nutzer verpflichtend aktiviert; siehe: http://www.alexandreviot.net/2017/04/03/office-force-add-ins-activation/

**Comment by zonky2** [comment]
phuu...
* habe von hier das 64er Paket gezogen https://www.microsoft.com/en-us/download/confirmation.aspx?id=35554 und extrahiert
* lt. "Instruction" den Ordner \admin nach C:\Program Files\Microsoft Office 15\root\office15 kopiert
* gpedit.msc gestartet

... die Vorlagen für Office wie im Screenshot bei http://www.alexandreviot.net/2017/04/03/office-force-add-ins-activation/ zu sehen, sind bei mir nicht da 

:(

**Comment by synthetrash** [comment]
Hm.. ist schon etwas her, aber eigentlich musst du die admx files unter `C:\Windows\PolicyDefinitions` schieben. Der admin-Folder ist für unser Vorhaben zu vernachlässigen. Und die Language-Files (adml) müssen unter `C:\Windows\PolicyDefinitions\en-US`.

**Comment by zonky2** [comment]
super - scheint zu funktionieren... die Dateien müssen bei Win7 unter `C:\PolicyDefinitions\...`
