### ISSUE TITLE
Gruppenruf für ausgehende Gespräche, eher ein Request aber ich kann hier keins eintragen

### ISSUE THREAD

**Issue by LurchiStromberg** [Kruemelino/FritzBoxTelefon-dingsbums#30]
Wenn ich einen Gesprächspartner anrufen möchte, dann stelle ich ja auf "verbinden über" das Telefon ein, über welches ich telefonieren möchte.
Wäre es möglich hier alle Telefone (oder nur die ISDN Telefone, oder bestimmte Telefone) als Verbindungsgeräte klingeln zu lassen?

Hintergrund ist, ich nutze 2 Headsets und einen Handapperat und je nach Ladezustand führe ich die Anrufe über die verschiedenen Endgeräte.
Wenn nun bei der Verbindung alle 3 gleichzeitig klingeln würden, könnte ich mir das Gerät aussuchen und müsste es nicht immer bei "verbinden über" erst auswählen.

Ich nutze seit geraumer Zeit jAnrufmonitor (ich dachte du entwickelst nichts mehr an FBDB und habe hier eine Ewigkeit nicht mehr nachgeschaut).
Dort kann man als Nebenstelle "alle ISDN Geräte" wählen.
Diese Nebenstelle erfüllt genau das, was ich gern auch bei FBDB haben möchte.
Dann kann ich nämlich jAnrufmonitor endlich in die ewigen Jagdgründe schicken!

Wäre toll wenn du da was machen kannst!

**Comment by Kruemelino** [comment]
Ist das noch relevant? Ist zwar schon ewig her.

**Comment by LurchiStromberg** [comment]
Hallo Gert!
Nö, ist nicht mehr relevant.

In meiner Version von FBDB hatten wir doch schon die Möglichkeit "erschaffen" über alle ISDN Geräte zu verbinden.
Das war es ja was ich wollte...

**Comment by Kruemelino** [comment]
Sehr gut.
Sollte ja in Version 5 somit auch funktionieren.
