### ISSUE TITLE
Weitere Funktionen > Anruflisten: Eintrag nach Neustart von OL wieder auf 10

### ISSUE THREAD

**Issue by zonky2** [Kruemelino/FritzBoxTelefon-dingsbums#31]
Weitere Funktionen > Anruflisten: Eintrag nach Neustart von OL wieder auf 10

hatte 20 eingetragen - nach übernehmen sieht man auch 20... nur nach Neustart ist die Einstellung futsch :(

V 3.10.6

**Comment by Kruemelino** [comment]
Version 3 wird nicht weiter unterstützt. Version 5 sollte das Problem nicht haben.
