### ISSUE TITLE
Kontaktupload wird nicht bestätigt

### ISSUE THREAD

**Issue by RalfRoemling** [Kruemelino/FritzBoxTelefon-dingsbums#34]
Wenn man einen Kontakt zur FB hochläd, erscheint keinerlei Rückmeldung. 
Weder beim Klick, noch über das Ergebnis.

Gut wäre eine Meldung "Upload Erfolgreich/Fehlgeschlagen/etc."

**Comment by Kruemelino** [comment]
Ich werde mir was überlegen.

**Comment by Kruemelino** [comment]
Ich habe mir das mal angeschaut. Momentan erfolgt nur eine Log Message. D. h. im Log stehen entsprechende Einträge. 
Da man auch mehrere Kontakte gleichzeitig hochladen kann, kann eine Meldung ja nicht bei jedem Kontakt erfolgen. Da wird man ja blöd. Für diese Meldung muss ich also den Code etwas umstricken.

**Comment by RalfRoemling** [comment]
Moin Gert, 
wieder was gelernt, mir war bisher nicht klar, dass man mehrere Kontakte hochladen kann. 

Danke :-)

**Comment by Kruemelino** [comment]
Nur, dass das in der aktuellen Version nicht funktioniert. 😉
