### ISSUE TITLE
Login-Fehler

### ISSUE THREAD

**Issue by zonky2** [Kruemelino/FritzBoxTelefon-dingsbums#35]
FBDB 5.0.1.1

gestern wurde anscheinend eine neue FW eingespielt Version 07.27 auf FB 7490

Fehlermeldung bei Aus/Einlesen der Telefone:

```
25.05.2021 11:16:03.017|Error|FBoxDial.SOAP.BaseFunctionsTR64|FritzBoxPOST|0|TR-064 Login-Fehler 401: X_AVM-DE_CreateUrlSID "Unauthorized"|
Exception: System.Net.WebException
Der Remoteserver hat einen Fehler zurückgegeben: (401) Nicht autorisiert.
Byte[] UploadDataInternal(System.Uri, System.String, Byte[], System.Net.WebRequest ByRef)
Status: ProtocolError;Response: System.Net.HttpWebResponse
   bei System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   bei System.Net.WebClient.UploadString(Uri address, String method, String data)
   bei FBoxDial.SOAP.BaseFunctionsTR64.FritzBoxPOST(Uri UniformResourceIdentifier, String SOAPAction, String ServiceType, XmlDocument SOAPXML, String& Response)
25.05.2021 11:16:03.017|Error|FBoxDial.SOAP.Service|Start|0|TR-064 Login-Fehler 401: X_AVM-DE_CreateUrlSID "Unauthorized"|
25.05.2021 11:16:03.020|Warn|FBoxDial.SOAP.FritzBoxTR64|GetSessionID|0|Keine SessionID der Fritz!Box erhalten. Rückgabewert: 0000000000000000|
```
Edit: gerade gesehen:
![FireShot Pro Webpage Screenshot #388 - 'FRITZ!Box 7490' - http](https://user-images.githubusercontent.com/1045318/119475219-3dafe080-bd4d-11eb-9c39-2f47c21e9288.jpg)

die FB 7490 hat aber zum Login nur ein PW und keinen Anmeldenamen...

**Comment by zonky2** [comment]
ggf. wieder einen Button zum Login-Test einbauen

**Comment by Kruemelino** [comment]
Grundsätzlich hat AVM beim Loginverfahren etwas geändert.

https://avm.de/service/schnittstellen/

Das Loginverfahren ohne Benutzername wird nicht mehr unterstützt. Das heißt es muss ein Benutzer angegeben werden. Bei den neuen Firmware-Versionen wird einer angelegt.

**Comment by zonky2** [comment]
> Wenn bislang die Anmeldeart „Anmeldung nur mit FRITZ!Box-Kennwort“ verwendet wurde, wird wäh-rend des Updates automatisch ein FRITZ!-Benutzer angelegt. Dieser FRITZ!-Benutzer hat einen zufällig gewählten Namen nach dem Schema fritz[0-9]{4}, also zum Beispiel fritz1234, fritz1337oder fritz0042.

Spannende Frage ist, wie ich bei meiner FB 7490 den Namen heraus bekomme... find ich nirgends :(

**Comment by zonky2** [comment]
ahh - weiterlesen hilft

Aufruf mit
`fritz.box/login_sid.lua?version=2`

zeigt

```
<SessionInfo>
<SID>0000000000000000</SID>
<Challenge>
2$60000$ba9760bd075ad5044cd54169b4c7b511$6000$63e042a10331b47e73416971fccdca92
</Challenge>
<BlockTime>0</BlockTime>
<Rights/>
<Users>
<User last="1">fritz1234</User>
</Users>
</SessionInfo>
```

**Comment by Kruemelino** [comment]
Das stimmt. Das steht ja auch so in der PDF. Ich werde trotzdem mal einen Login-Test ausarbeiten. Vielleicht stolpern dann weniger darüber.
