### ISSUE TITLE
[5.0.1.1] Telefonnummern mit führender Null geht Wählpopup nicht

### ISSUE THREAD

**Issue by zonky2** [Kruemelino/FritzBoxTelefon-dingsbums#41]
V. 5.0.1.1

OL 2019

~~Telefonnummern mit Landesvorwahl geht Wählpopup nicht~~
Telefonnummern mit führender Null geht Wählpopup nicht

wenn die Nummern so sind gehts

![Zwischenablage03](https://user-images.githubusercontent.com/1045318/122883596-a8007480-d33d-11eb-8aab-cb92bdc05e4a.jpg)

wenn man einen Doppelklick auf die Nummer macht und schließt, steht ein `+49` davor - dann geht das Popup zum Wählen nicht auf.

**Comment by Kruemelino** [comment]
Passiert das gleiche wenn du die 0 in der Vorwahl weg lässt?

Ich habe neulich festgestellt, dass eine falsch angegebene Nummer (+49**0**1512 232....) nicht korrekt aufgelöst wurde.

**Comment by zonky2** [comment]
o.k. stimmt... mit +49 (511) 84... und +49 (1512) 232... gehts

**Comment by Kruemelino** [comment]
Dann hab ich das Problem vermutlich schon behoben.
Ich schließe mal das Issue. Es gibt schon eine Testversion. Ich lade sie gleich als PreRelease hier hoch. Du kannst ja noch mal testen. Dann schließen wir das hier.

**Comment by zonky2** [comment]
o.k. - habe das auch nochmal mit dem "Testbereich" getestet - aktuell geht der nicht mit führender Null bei Vorwahl

**Comment by zonky2** [comment]
5.0.1.4 - sieht gut aus... Popup geht mit "Null" auch wieder auf und Telefonnummern-Test geht auch damit

**Comment by Kruemelino** [comment]
> 5.0.1.4 - sieht gut aus... Popup geht mit "Null" auch wieder auf und Telefonnummern-Test geht auch damit

Danke für die Rückmeldung
