### ISSUE TITLE
Mail versenden blockiert

### ISSUE THREAD

**Issue by atwcc** [Kruemelino/FritzBoxTelefon-dingsbums#45]
Hallo Gert,
ich habe OL2019/x32 im Einsatz mit FBDB Release 5.0.1.12.
Sobald das Add-In aktiviert ist, verlassen meine Mails den Postausgang nicht mehr, d.h. sie werden nicht gesendet.
Schalte ich FBDB aus (Add-In deaktiviert) so klappt es mit dem Versand wieder.
Alle anderen Funktionen von FBDB arbeiten perfekt.
Hast du da irgendeine Idee, was das sein könnte?
Schöne Grüsse, Gernot

**Comment by atwcc** [comment]
Warten wir mal ab. Es macht wenig Sinn grossen Aufwand zu treiben so lange es nur ein Einzelfall ist/bleibt.
Vielen Dank.

**Comment by Kruemelino** [comment]
[FBDBSetup_5.0.1.13_211016-1357.zip](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/files/7357490/FBDBSetup_5.0.1.13_211016-1357.zip)

Probiert mal diese Version. 
Ich habe noch keine wirkliche Lösung gefunden. Ich bezweifle, dass es ein Bug im Addin ist. Das ist ein generelles Outlook Problem. Ich habe ein bestehendes Feature erstmal rausnehmen müssen. Ich hoffe das klappt. Ansonsten muss ich noch mal ran.

**Comment by Kruemelino** [comment]
In der neuen Version, müsst ihr in den Grundeinstellungen die entsprechende Funktion aktivieren. Erst dann werden die E-Mails bei der Überprüfung der Ribbons nicht mit einbezogen.
![image](https://user-images.githubusercontent.com/4273483/137634181-4ac5c37c-08a8-4357-9ab7-a19a708fbebd.png)
