### ISSUE TITLE
Wahlhilfe für Chrome?

### ISSUE THREAD

**Issue by krheinwald** [Kruemelino/FritzBoxTelefon-dingsbums#46]
In Chrome gibt es einen Handler für tel:xxxxxxxxxx-Links, in den man sich wohl einhängen kann, wie dieser Screenshot am Beispiel des MyPhoneExplorer (Sync-Tool Outlook/Android) zeigt.
![Screenshot 2021-10-20 131903](https://user-images.githubusercontent.com/452679/138083578-c365faae-0636-4d75-9171-3c7546f1f865.png)
Es wäre sehr schön, wenn in dieser Liste auch die FritzBox auftauchen würde 🙏

**Comment by Kruemelino** [comment]
Ich glaube, das kann ich hier nicht realisieren. Es hat mit dem Addin nichts zu tun und bedarf einer Entwicklung eines Addins für Chrome/Firefox etc. Das wäre ein separates Projekt für das ich keine Kapazitäten geschweige denn Ahnung wie das geht.

Sorry
