### ISSUE TITLE
Sternchen bei Rückruf und Wahlwiederholung ist weg

### ISSUE THREAD

**Issue by zonky2** [Kruemelino/FritzBoxTelefon-dingsbums#47]
Sternchen bei Rückruf und Wahlwiederholung ist weg - "früher" war bei der Nummer von der man angerufen wurde bzw. die man angerufen hat ein Sternchen...

**Comment by Kruemelino** [comment]
Das mit dem Stern hab ich anders gelöst. Die letzte Nummer ist jetzt Fett gedruckt. (Mit dem Stern hab ich leider auf die Schnelle nicht gelöst bekommen)

**Comment by zonky2** [comment]
o.k. - ab welcher Version? ich habe die 5.0.1.7

**Comment by Kruemelino** [comment]
Einer der letzten. Probier mal die aktuelle hier von github

**Comment by zonky2** [comment]
1+
