### ISSUE TITLE
OL 2019 - Anrufmonitor startet erst bei zweitem OL-Start

### ISSUE THREAD

**Issue by zonky2** [Kruemelino/FritzBoxTelefon-dingsbums#48]
Wenn ich nach einem Rechnerneustart OL starte, startet der Anrufmonitor nicht mit - auch die Konfig wird nicht geladen, da alle Einstellungen leer sind. Schließe ich OL und starte neu, ist alles o.k.

FBDB habe ich schon neu installiert und auch verschiedene Versionen getestet - Phänomen bleibt so...

hmm?!?

**Comment by Kruemelino** [comment]
Im Log steht dazu vermutlich auch nichts. 
Klingt ja fast so, als wenn er beim ersten mal die Einstellungsdatei nicht lesen kann.

**Comment by zonky2** [comment]
Im Log konnte ich nix finden - ich mache vor nächsten Rechnerstart die Logdatei mal leer...

**Comment by zonky2** [comment]
V 5.0.1.16

getestet... beim ersten Start tut sich "nix" - Logfile bleibt leer; wenn man das Konfigfenster aufmacht, ist da auch alles leer...

OL geschlossen => OL geöffnet: wieder alles ok und Log geht dann auch los mit

```
27.11.2021 16:13:04.418|Debug|FBoxDial.OptionenViewModel|MoveNext|1|0|Lade die Daten aus der XML-Datei in das ViewModel Optionen|
...
```

**Comment by Kruemelino** [comment]
Danke für das Testen. Leider weiß ich nicht, wie ich da helfen kann. Für mich macht es den Eindruck, dass den Lese- und Schreibvorgang irgendwie blockiert wird. Ein Virenscanner? Den Dateipfad zu verschieben wird im Addin aufwendig. Zumal das Roaming Verzeichnis genau dafür gemacht ist.

Ich bin ratlos

**Comment by zonky2** [comment]
nun ja, so oft starte ich den Rechner nicht... ;-)
