### ISSUE TITLE
Outlook-Absturz

### ISSUE THREAD

**Issue by silas229** [Kruemelino/FritzBoxTelefon-dingsbums#50]
Hallo,
ich habe mir einen Laptop gekauft. Seitdem in Outlook Fritzbox dingsbums installiert wurde, lässt es sich nicht mehr öffnen, **solange der Laptop beim Start von Outlook mit dem Internet verbunden ist**. Wenn ich das WLAN erst ausschalte und nach dem Start wieder einschalte, funktioniert alles reibungslos.

Das habe ich in der Ereignisanzeige gefunden:
```
Anwendung: OUTLOOK.EXE Frameworkversion: v4.0.30319 Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet. Ausnahmeinformationen: System.NullReferenceException bei FBoxAPI.Service.Start(FBoxAPI.Action, System.Collections.Hashtable, FBoxAPI.TR064HttpBasics, System.Net.NetworkCredential) bei FBoxAPI.FritzBoxTR64.TR064Start(SCPDFiles, System.String, System.Collections.Hashtable) bei FBoxAPI.X_contactSCPD.GetCallBarringList(System.String ByRef) bei FBoxDial.Telefonbücher.FritzBoxTelefonbuch+VB$StateMachine_8_LadeSperrliste.MoveNext() bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) bei System.Runtime.CompilerServices.TaskAwaiter`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult() bei FBoxDial.FritzBoxRufsperre+_Closure$__18-0+VB$StateMachine___Lambda$__0.MoveNext() bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) bei System.Runtime.CompilerServices.TaskAwaiter`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult() bei FBoxDial.FritzBoxRufsperre+VB$StateMachine_18_BlockTellowsNumbers.MoveNext() bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) bei System.Runtime.CompilerServices.TaskAwaiter`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult() bei FBoxDial.Journal+VB$StateMachine_6_AutoBlockListe.MoveNext() bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() bei System.Threading.ThreadPoolWorkQueue.Dispatch()
```
Hat noch jemand anderes dieses Problem oder einen Quickfix, um das Problem zu beheben?

**Comment by Kruemelino** [comment]
Kannst du bitte das Verhalten genauer beschreiben? Ich verstehe nicht 100% was du meinst und kann somit das Problem nicht nachstellen.

1. Du bist mit der Fritz!Box verbunden.
2. Du startest Outlook und es kommt zum Absturz?

oder 

1. Du bist **nicht** mit der Fritz!Box verbunden.
2. Du startest Outlook und es kommt zum Absturz?

Laut Fehler ist es ein Problem in der TR-064 Anbindung beim herunterladen der Sperrliste aus der Fritz!Box.

**Comment by silas229** [comment]
Hi, es ist alles eingestellt und funktioniert ansonsten auch. Kann man das Herunterladen ausschalten?

**Comment by Kruemelino** [comment]
Du kannst die Kontaktsuche in den Fritz!Box Telefonbüchern ausschalten. Dann lädt er die beim Outlookstart nicht herunter. 

Kommt es auch zum Absturz, wenn du die Fritz!Box Daten öffnest? Was ist bei eingehenden Telefonaten? Kommt es auch zum Absturz?

Ich hab einen Verdacht woran es liegt. Aber erstmal kommt Weihnachten.

**Comment by Kruemelino** [comment]
Fehler gefunden: Automatische Aktualisieren der Sperrliste aus Tellows ist das Problem.

**Comment by silas229** [comment]
Danke👍🏼

**Comment by Kruemelino** [comment]
Am besten du deaktivierst die Option erstmal. Bis zu einer neuen Version dauert es noch.
