### ISSUE TITLE
V 5.0.3.10 & OL 2019: bei Auflegen schmiert OL ab

### ISSUE THREAD

**Issue by zonky2** [Kruemelino/FritzBoxTelefon-dingsbums#58]
V 5.0.3.10 & OL 2019: bei Auflegen schmiert OL ab

Logfile:
```
....
16.07.2022 12:36:53.393|Info|FBoxDial.Anrufmonitor|AnrMonTCPClient_Message|5|0|AnrMonAktion: 16.07.22 12:36:54;DISCONNECT;0;689;|
16.07.2022 12:36:53.449|Info|FBoxDial.Telefonat|ErstelleJournalEintrag|5|0|Journaleintrag im Ordner Journal (Nur dieser Computer) (Store: info@xyz.de) erstellt: 16.07.2022 12:25:00, Nicht erfolgreicher Anruf zu (0 30) 0 14 60, 11|
16.07.2022 12:36:53.576|Warn|FBoxAPI.WebFunctions+VB$StateMachine_14_PostBase|PostBase|19|250|SOAPFault: ' https://192.168.178.1:49443/upnp/control/x_tam '; RequestContent: 
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:GetMessageList xmlns:u="urn:dslforum-org:service:X_AVM-DE_TAM:1">
      <NewIndex>-40</NewIndex>
    </u:GetMessageList>
  </s:Body>
</s:Envelope>
Response:
<?xml version="1.0"?>
 <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<s:Fault>
<faultcode>s:Client</faultcode>
<faultstring>UPnPError</faultstring>
<detail>
<UPnPError xmlns="urn:dslforum-org:control-1-0">
<errorCode>713</errorCode>
<errorDescription>SpecifiedArrayIndexInvalid</errorDescription>
</UPnPError>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>|
16.07.2022 12:36:53.576|Debug|FBoxAPI.Serializer+VB$StateMachine_8_DeserializeAsyncFromPath`1|DeserializeAsyncFromPath|5|160|Deserialisierung von Pfad  |
16.07.2022 12:36:53.576|Error|FBoxAPI.Serializer|CheckXMLData|15|69|Die übergebenen XML-Datan sind leer.|
16.07.2022 12:36:53.576|Error|FBoxAPI.Serializer|Deserialize|15|120||
Exception: System.Exception
Fehler beim Deserialisieren:  kann nicht deserialisert werden.
```

OL startet anschließend wieder neu

**Comment by Kruemelino** [comment]
Ich habe das Problem an mehrere kleine Fehler zurückführen können.
Prüfe mal bitte, ob die Telefoniegeräte richtig eingelesen sind. Ein Anrufbeantworter (TAM) scheint nicht richtig erfasst zu sein. Die AnrMonID darf hier nicht 0 sein. Werte 40+ sind korrekt. Der übergebene Wert für `NewIndex` von -40 kann nicht korrekt sein.

``` xml
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:GetMessageList xmlns:u="urn:dslforum-org:service:X_AVM-DE_TAM:1">
      <NewIndex>-40</NewIndex>
    </u:GetMessageList>
  </s:Body>
</s:Envelope>
```
Die Fritz!Box liefert korrekterweise einen Fehler: `SpecifiedArrayIndexInvalid`. Nachfolgend wird versucht ein leeren String zu Deserialisieren (geht natürlich schief). Zu guter Letzt wird auf ein Datenobjekt, was Nothing (bzw. null) ist zugegriffen.

Den Fehler kann ich einfach erfassen. Bitte prüfe das Thema mit dem Anrufbeantworter. Danke

**Comment by zonky2** [comment]
bei Typ `TAM` ist die Spalte `ID` immer `0` 

es gibt die Abschnitte mit `Name` "Fax ohne Rufnummer mit allen Telefonnummern und dann das Ganze noch 3x mit allen Rufnummern, aber ohne Eintrag bei `Name` ... auch Kurzwahl stand überall auf `0`

Nach erneutem Einlesen sind alle `TAM` mit `ID` 40 und 41, Kurzwahl ist 600 aufwärts und die Sektionen ohne `Name` sind weg...

Mal sehen, wie sich das auswirkt.

Ich hatte die V 5.0.3.10 auf eine V 5.0.1.x aufgebügelt.

**Comment by Kruemelino** [comment]
Ja, ich hatte vor geraumer Zeit das Einlesen der Telefone überarbeiten müssen. Insbesondere die TAM, da man ja auch die Nachrichten direkt anhören kann. 
Wenn ein Anrufbeantworter ein Telefonat entgegennimmt, wird als Geräte die 40 übermittelt. 
Wenn das Gespräch beendet wurde, hat die Fritz!Box ggf. eine Nachricht aufgenommen.
Das Addin, prüft nun ob dies der Fall ist. Hierfür wird via TR-064 die Nachrichtenliste des Anrufbeantworters (`GetMessageList`) abgerufen. Dafür muss die ID dies TAM übermittelt werden. Die ist aber dafür nicht 40 sondern 0 (bei 41 ist es 1 usw.). Es wird 40 von der ID abgezogen (Fehler: `0 - 40 = -40`). Wie schon gesagt, der Fehler lag an einer `NullReferenceException`. 

Zusätzlich habe ich die [FBoxAPI](https://github.com/Kruemelino/FBoxAPI/commit/9b65c1eeac74935b8947463cc8490038ab88d003) angepasst, so dass im Fehlerfall keine null-Datentypen übermittelt werden.

Zu einem Absturz sollte bei dir nicht mehr kommen, da die Ursache behoben ist. Danke für die Fehlerbeschreibung und für die Meldung.

**Comment by Kruemelino** [comment]
Danke für die Unterstützung :)
