### ISSUE TITLE
Kleine Bugs in 5.0.3.10

### ISSUE THREAD

**Issue by zonky2** [Kruemelino/FritzBoxTelefon-dingsbums#59]
Kleine Bugs in 5.0.3.10:

* beim Popup zum Wählen muss ich immer aus dem Select meinen (einen) Namen auswählen - die Auswahl wird nicht gemerkt oder man kann in der Konfig ein Default setzen
* Einstellungen > Telefone: der Inhalt kann nicht mit der Maus gescrollt werden

**Comment by Kruemelino** [comment]
Hi,

- ja, du kannst in den Einstellungen ein Standardtelefon auswählen. Das ist die erste Spalte im Grid der eingelesenen Telefone
- Bug oder Feature. Mich hat es gestört, dass das Mausrad das Grid/Treeview gescrollt hat und nicht die ganze Seite. Da hatte ich es deaktiviert. Ist nicht optimal. Ich schau es mir noch mal an.

**Comment by zonky2** [comment]
> ja, du kannst in den Einstellungen ein Standardtelefon auswählen. Das ist die erste Spalte im Grid der eingelesenen Telefone

ahh... die Spalte ohne Bezeichnung ;-)

**Comment by Kruemelino** [comment]
😁 Es gibt ein ScreenTip auf dem tanellenkopf

**Comment by zonky2** [comment]
uff... 

btw: da steht

> Ist kein Telefon ausgewählt, wird das zuletzt verwendete genommen

das kann ich nicht bestätigen - musste immer neu auswählen

(Button "Anrufen" könnte disabled sein bis im Select was steht - ansonsten kommt "Fehler" und ich dachte die Nummer geht nicht...)

**Comment by Kruemelino** [comment]
Normalerweise wird die ID des zuletzt genutzten Telefons immer gespeichert: `UsedTelefonID`. Allerdings wird das Speichern nur durchgeführt, wenn der Wählvorgang erfolgreich war (Was ich mir dabei gedacht habe, kann ich nicht sagen.)
Das Standard-Telefon wird im Attribut `StdTelefon` in den Einstellungen gespeichert.

Hab ich dich richtig verstanden, dass bei dir kein Telefon vorausgewählt ist? Wenn das der Fall ist, kann ein Telefonat eigentlich nicht gestartet werden.

**Comment by Kruemelino** [comment]
Hallo zonky2,

GIbt es hier in der aktuellen Version noch Probleme?

VG

Gert

**Comment by zonky2** [comment]
da ich diesmal alles richtig eingestellt habe, nicht
