### ISSUE TITLE
Rechtschreibfehler

### ISSUE THREAD

**Issue by Kruemelino** [Kruemelino/FritzBoxTelefon-dingsbums#6]
Hier bitte alle Auffälligkeiten hinein.

Danke

**Comment by xantippe** [comment]
[3.7.12]
Reiter Phoner:
* nach Festnetz Leerzeichen zu viel => "Festnetz, zu"
* nach Gegenstellen Leerzeichen zu wenig => "Gegenstellen. Phoner"
* nach Teilnehmeranschlüssen Leerzeichen zu wenig => "Teilnehmeranschlüssen, an"
* nach Teilnehmeranschlußleitungen Komma zu viel => "Teilnehmeranschlußleitungen und"
