### ISSUE TITLE
Minor Typo V5.0.3.15

### ISSUE THREAD

**Issue by emesevo** [Kruemelino/FritzBoxTelefon-dingsbums#61]
Ich denke, dass in dem Dialog "Fritz!Box Daten" an zwei Stellen das Wort "Journalimport" stehen soll, aber das "r" beide Male verlorengegangen ist.

![image](https://user-images.githubusercontent.com/32421489/196531466-c2cffbd4-36f8-4b64-9344-31accedcf8d1.png)

**Comment by emesevo** [comment]
Falls das weiterhilft: Habe es gerade hinbekommen in VS mal die Solution zu durchsuchen - das "r" im "Journalimport" fehlt da wohl einige Male ... bin mir leider nicht sicher genug im Umgang mit VS und .NET, sonst würde ich das r selber einfach einsetzen.

![image](https://user-images.githubusercontent.com/32421489/196536075-32f60a20-b937-40be-9d7b-fc9e4d1dea6e.png)

**Comment by Kruemelino** [comment]
Danke für den Hinweis. Da sieht man mal wie lange so ein kleiner Tippfehler, der vermutlich durch Copy&Paste entstanden ist, enthalten sein kann. 

Bei der nächsten Version wird das "r" vorhanden sein.
