### ISSUE TITLE
2 Faktor Authentifizierung im aktuellen FRITZ! Labor

### ISSUE THREAD

**Issue by manuquadrat** [Kruemelino/FritzBoxTelefon-dingsbums#62]
Hallo,
mir ist bei der aktuellen Einrichtung aufgefallen, dass mit der aktuellen FRITZ! Labor Firmware (7.39-101676) die 2 Faktor Authentifizierung scheinbar nicht mehr deaktiviert werden kann, sie kann lediglich auf einen TOTP basierten Ansatz umgestellt werden. Anrufe schlagen mit der dementsprechenden Fehlermeldung fehl.
Ist bekannt, ob es hierfür einen Workaround gibt / geben wird? Was bedeutet das für die Zukunft dieses Addins?
Viele Grüße

**Comment by Kruemelino** [comment]
Danke für den Hinweis. Das ist jedoch nicht so schön und wäre mir neu. Hast du das im IPPF mal bestätigen lassen?

Soweit ich weiß, wird die 2FA nur beim Wechsel des Telefons beim Wählen benötigt. Das Telefonieren über die Wählhilfe war bis dahin nicht betroffen. Falls sich das geändert hat, bitte Bescheid geben.

Für mich bedeutet dies, dass ich mir diese [Spezifikation](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_auth.pdf) von AVM zu Gemüte führen muss. Es wird darauf hinaus laufen, dass man auf einem DECT-Gerät (oder ggf. einem FON und S0) einen Code eingeben muss. 

Ich habe leider nur eine 7490 auf der ich die 2FA ausgeschalten habe.

**Comment by Kruemelino** [comment]
Mittlerweile habe ich die Bestätigung, dass die 2FA nicht mehr deaktivierbar ist. 
Ich habe die FBoxAPI Schnittstelle bereits in Bearbeitung, so dass die 2FA abgewartet wird. Leider hänge ich an einem seltsamen Phänomen: Die Authentifizierung wird gestoppt, wenn ich auf einen Button der Box drücke. Eigentlich sollte die Authentifizierung damit vollendet werden. 

Hier noch ein Auzug aus dem Changelog der 7590 mit 7.50:
```
## [6] zusätzliche Bestätigung

Die zusätzliche Bestätigung für bestimmte Einstellungen und Funktionen kann nach dem Update nicht mehr deaktiviert werden.
Sofern die zusätzliche Bestätigung vor dem Update deaktiviert war, bleibt dieser Zustand jedoch auch nach dem Update erhalten.
AVM empfiehlt aus Sicherheitsgründen, die zusätzliche Bestätigung stets zu nutzen.
Um auch aus der Ferne zusätzlich geschützte Einstellungen ändern zu können,
kann für die zusätzliche Bestätigung auch der TOTP-Standard mit Einmalkennwörtern genutzt werden.
Dafür können ein kostenlos erhältlicher Passwortmanager oder eine separate App wie beispielsweise der Google Authenticator genutzt werden.```

**Comment by manuquadrat** [comment]
Danke für die Bestätigung. Würde dies dann implizieren, dass jede Aktion an der Box bestätigt werden muss, oder lediglich die erste Aktion? Ansonsten wird das TOTP-Secret auch bei Erstellung angezeigt, womit (theoretisch) eine eigenständige Code-Generierung möglich sein sollte. Da ich leider keine Erfahrung mit der Erstellung von Outlook Add-Ins habe, kann ich nicht beurteilen, ob sich die Implementierung lohnen — bzw. überhaupt funktionieren würde.
Viele Grüße

**Comment by Kruemelino** [comment]
Es ist eigentlich eher ein Thema in der [FBoxAPI](https://github.com/Kruemelino/FBoxAPI). Mittlerweile habe ich da die 2FA implementiert. 
Grundsätzlich sind nicht alle Aktionen der TR-064 Schnittstelle betroffen. Für das Addin ist es soweit ich weiß "nur" die Action `X_AVM-DE_DialSetConfig` aus der `X_VoIP` betroffen. Mit dieser Action wird das Telefon der Wählhilfe umgestellt. Ich will aber nicht ausschließen, das weitere Funktionen betroffen sind.

Du kannst mal testen: Es ist wirklich eine Testversion. Die Signalisierung ist noch nicht ideal.
[FBDBSetup_5.0.3.17_221203-1934.zip](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/files/10147122/FBDBSetup_5.0.3.17_221203-1934.zip)

**Comment by Kruemelino** [comment]
Hast du die letzte Version mal getestet? Die fertige 2FA habe ich am 24.12. als Vorabversion veröffentlicht.

**Comment by manuquadrat** [comment]
Super, danke für das Update. Ich werde die nächsten Tage hoffentlich etwas Zeit zum testen finden und kann dann Feedback geben.
Viele Grüße

**Comment by krheinwald** [comment]
Habe gestern von Office 2019 auf 2021 aktualisiert und daraufhin seit langem mal wieder das Wählen über das Outlook-Plugin getestet, dass bisher immer mit Fehler abbrach. Es wird jetzt bei *jedem* Anruf eine Bestätigung (*xxxxx wählen oder Taste an der Box) verlangt?

Der 2FA-Test in Testbereich hat keine für mich ersichtliche Funktion.

**Comment by Kruemelino** [comment]
Hallo @krheinwald,

ich benötige weitere Informationen. Eigentlich sollte(!) der die 2FA nur beim Wechsel des Telefones der Wählhilfe ausgelöst werden. Danach sollte(!) die Authentifizierung eine Weile gültig sein. 

- Kannst du mir mal ein Log zukommen lassen? 
- Worauf ist die Wählhilfe der Fritz!Box eingestellt?
<img width="907" alt="image" src="https://user-images.githubusercontent.com/4273483/215262661-d8035842-1d91-4c26-92aa-a11431ac4aef.png">
- Stellst du das Telefon über den Wählclient jedes mal um?

Der 2FA-Test in Testbereich diente für mich zum Auslösen einer 2FA. Den hab ich gerade entfernt.

**Comment by krheinwald** [comment]
Ok, das Problem saß vor der Tastatur. Kannte diese Einstellung der FB gar nicht. Nach Umstellen auf das verwendete Headset konnte eine Wahl ohne 2FA ausgelöst werden.

**Comment by Kruemelino** [comment]
Die 2FA kommt nur, wenn du das Gerät wechselst. 
Ich denke es ist so (da bin ich mir nicht 100% sicher): Wenn man in der Fritz!Box nichts ausgewählt hat, ist die Wählhilfe deaktiviert. Dann wird bei jedem Fall die 2FA ausgelöst.
