### ISSUE TITLE
FBDBSetup_5.0.3.19_230108-1126  ///  Fehler beim Start von Outlook

### ISSUE THREAD

**Issue by atwcc** [Kruemelino/FritzBoxTelefon-dingsbums#64]
Beim Start von Outlook ergibt sich nach Installation von FBDBSetup_5.0.3.19_230108-1126 ein Laufzeitfehler.
Habe testhalber schon das Verzeichnis unter ..\AppData\Roaming\Fritz!Box Telefon-Dingsbums\ neu erstellen lassen, ändert leider nichts.
![fehler](https://user-images.githubusercontent.com/90832180/211286207-1715d0d7-e2ef-4fba-974c-551c4a227268.jpg)

Schöne Grüsse, Gernot

**Comment by Kruemelino** [comment]
Das ist der Ribbon im Termin für die Anruferinnerung. Ich muss das prüfen, wo der Fehler liegt. Welche Outlook-Version hast du?

**Comment by atwcc** [comment]
Vielen Dank für deine schnelle Rücknmeldung.
Microsoft Office Professional Plus 2019 habe ich installiert.

**Comment by Kruemelino** [comment]
Das Problem scheint hier zu liegen:
https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/blob/34fc9ac5fe84cd62ff61053d97125351ddd5e9b5/FBoxDial/Ribbon/RibbonXML/RibbonExplorer.xml#L140-L146

Es handelt sich um ein Ribbon zu "Kalendertools" von Terminen. Es kann sein, dass es derartige Funktionen in deiner Outlook-Version nicht gibt. Ich gebe mir Mühe eine Lösung zu erarbeiten. Momentan fehlt mir die Zeit. Schau erstmal, ob du eine alte Version verwenden kannst.

**Comment by Kruemelino** [comment]
Ich hab mir das noch mal angeschaut. Leider kann ich den Fehler nicht nachvollziehen. Auf meinem 365 und bei einer virtuellen Maschine mit Office 2010 tritt der Fehler nicht auf. Auf ein Office 2019 kann ich leider nicht zugreifen.
Es ist auch sehr schwer, den Fehler zu finden.
Ich kann erstmal nur eine Version erstellen, in der das ``TabSetAppointment`` nicht enthalten ist:
[FBDBSetup_5.0.3.19_230115-1045.zip](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/files/10419875/FBDBSetup_5.0.3.19_230115-1045.zip)

**Comment by atwcc** [comment]
Habe die Version FBDBSetup_5.0.3.19_230115-1045 installiert. Allerdings kommt es beim Start von Outllook wieder zur identischen Fehlermeldung ...

**Comment by Kruemelino** [comment]
Hast du die alte Version vorher händisch deinstalliert? Es kann sein, dass es weiterhin die alte Version ist. Da die Versionsnummer gleich ist, kann das passiert sein.

**Comment by atwcc** [comment]
Habe jetzt die 5.0.3.19_230115-1045 nochmals über "Programme hinzufügen oder entfernen" deinstalliert. Zudem noch das Verzeichnis unter ..\AppData\Roaming\Fritz!Box Telefon-Dingsbums\ entfernt. Im Anschluss die Version FBDBSetup_5.0.3.19_230115-1045 installiert. Dennoch, die Fehlermeldung beim Start von Outllook ist wieder da.
Gibt es noch andere Pfade, welche ich löschen sollte, event. auch Registry-Einträge?

**Comment by atwcc** [comment]
Habe es nochmals mit dem File aus dem vorangegangenen Link (FBDBSetup_5.0.3.20_230203-1644.zip) getestet ... 
Direkt beim Start kommt aber wieder exakt die gleiche Meldung wie oben angeführt.

**Comment by Kruemelino** [comment]
Ups... Könnte mein Fehler gewesen sein.

Ich hab gerade einen Tippfehler gefunden. Ein anderes Ribbon hieß `TabSetAppointment`, was eigentlich `TabAppointment` heißen soll.

[FBDBSetup_5.0.3.20_230204-1523.zip](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/files/10608855/FBDBSetup_5.0.3.20_230204-1523.zip)

**Comment by atwcc** [comment]
Habe es gerade ausprobiert - scheint nichts geändert zu haben - Fehlermeldung lautet jetzt dafür auch auf "TabAppointment".
![grafik](https://user-images.githubusercontent.com/90832180/216773483-ad1aec2a-3c0f-4271-a557-14ef6943da71.png)

**Comment by Kruemelino** [comment]
ich fress' ein Besen!

Ich Hab den gesamten Ribbon `TabAppointment` rausgeworfen.
[FBDBSetup_5.0.3.20_230204-1601.zip](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/files/10608922/FBDBSetup_5.0.3.20_230204-1601.zip)

**Comment by atwcc** [comment]
So ein Besen schmeckt gar nicht mal so gut - habe ich auch schon probiert  :-)
Leider bleibt der Fehler, aber wenn ich zurückgehe auf Version FBDBSetup_5.0.3.16_221112-1744 dann läuft alles.

Sorry für den Stress.

**Comment by Kruemelino** [comment]
Jetzt gibt es keine `TabSetAppointment` oder `TabAppointment` im Explorer mehr. Was schade ist. Ich hab aber den Eindruck, dass sich Outlook 2019 etwas zickig hat.

[FBDBSetup_5.0.3.20_230204-1619.zip](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/files/10608945/FBDBSetup_5.0.3.20_230204-1619.zip)

**Comment by atwcc** [comment]
Es muss wohl was anderes sein. Habe jetzt wirklich alles zuerst noch deinstalliert und dann deine neue Version FBDBSetup_5.0.3.20_230204-1619 installiert - die Fehlermeldung kommt wieder.
Mit der zuvor genannten Version FBDBSetup_5.0.3.16_221112-1744 startet Outlook fehlerlos.

**Comment by Kruemelino** [comment]
Ich geb da nicht auf. Wenn eine Fehlermeldung `TabSetAppointment` oder `TabAppointment` immernoch kommt, wundert mich das sehr. Es gibt keine Steuerelemente mit dieser ID mehr.


[FBDBSetup_5.0.3.20_230204-1628.zip](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/files/10608961/FBDBSetup_5.0.3.20_230204-1628.zip)

**Comment by atwcc** [comment]
Bin dabei und helfe dir gerne. Muss dann aber für heute abbrechen, bin morgen wieder im Büro zum testen.
Aktuell ist der Fehler noch da (Version FBDBSetup_5.0.3.20_230204-1628).
![grafik](https://user-images.githubusercontent.com/90832180/216776137-1ff4019b-adaf-47bb-be79-84bdbb7230b7.png)

**Comment by Kruemelino** [comment]
Ok. Danke schon mal. 

Das ist frustrierend. Ich suche nochmals genauer nach. Es ist verwunderlich.

**Comment by atwcc** [comment]
Habe tatsächlich vor der Deinstallation das Addin nicht separat aus Outlook entfernt, jetzt aber mal so durchgeführt.
Im Anschluss habe ich zudem das Verzeichnis unter ..\AppData\Roaming\Fritz!Box Telefon-Dingsbums\ entfernt und erst dann deine letzte Version "FBDBSetup_5.0.3.20_230204-1643.zip" installiert.
Aber leider, auch hier das gleiche Ergebnis - die Fehlermeldung ist wieder da.
Wie gesagt, installiere ich Version FBDBSetup_5.0.3.16_221112-1744 dann kommt keine Fehlermeldung.

**Comment by Kruemelino** [comment]
Das kann ja eigentlich gar nicht sein. 
Ich denke, dass das Addin irgendwie doch noch vorhanden ist. Kannst du mal prüfen, ob das der Fall ist?

Deinstalliere die Version und schau mal im Outlook, ob es noch geladen wird. Es kann auch in den deaktivieren Elementen vorhanden sein.

**Comment by atwcc** [comment]
Die Liste der deaktivierten Element ist nach Deinstallation und entfernen des Addins leer.
Neuer Versuch, leider immer das gleiche Ergebnis - langsam weiss ich auch keinen Rat mehr.

![grafik](https://user-images.githubusercontent.com/90832180/216831815-e2a734e9-bf3a-414c-ba83-18414f5f77cf.png)

**Comment by Kruemelino** [comment]
Ich weiß es auch nicht mehr. Die letzte Version, die ich gestern erstellt hatte, hat keine Ribbons für Termine (Appointments). Da ist alles entfernt. 

Ich könnte eine Version machen, die die zu ladende XML ins Log (als Trace) rausschreibt. Die Ribbons für Termine sind hier aber wieder aktiv. 
[FBDBSetup_5.0.3.20_230205-1818.zip](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/files/10611664/FBDBSetup_5.0.3.20_230205-1818.zip)

**Comment by atwcc** [comment]
Hallo Gert,

 

anbei das Log-File wie gewünscht – bitte bestätige mir den Empfang – vielen Dank.

 

Schöne Grüsse, Gernot WOLF

 

ALU Technik WOLF

Ing.  Gernot  Wolf

Wallenmahd    29

A - 6850  Dornbirn

A  U  S  T  R  I  A

T  +43 5572 372020-0

F  +43 5572 372020-5

 

Von: Gert Michael ***@***.***> 
Gesendet: Sonntag, 5. Februar 2023 18:20
An: Kruemelino/FritzBoxTelefon-dingsbums ***@***.***>
Cc: atwcc ***@***.***>; Author ***@***.***>
Betreff: Re: [Kruemelino/FritzBoxTelefon-dingsbums] FBDBSetup_5.0.3.19_230108-1126 /// Fehler beim Start von Outlook (Issue #64)

 

Ich weiß es auch nicht mehr. Die letzte Version, die ich gestern erstellt hatte, hat keine Ribbons für Termine (Appointments). Da ist alles entfernt.

Ich könnte eine Version machen, die die zu ladende XML ins Log (als Trace) rausschreibt. Die Ribbons für Termine sind hier aber wieder aktiv.
FBDBSetup_5.0.3.20_230205-1818.zip <https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/files/10611664/FBDBSetup_5.0.3.20_230205-1818.zip>

**Comment by Kruemelino** [comment]
Log ist angekommen. Danke. (Ich sehe darin einen anderen Fehler bei deiner Vorwahl, den ich später mal prüfen muss.)

Mir fehlen darin die Einträge, die ich gestern haben ergänzt habe. Es ist halt wieder ein Indiz, dass nicht die Version geladen wird, die bereitgestellt wurde. 

Ich bin im Büro und kann erst heute Abend wieder was machen.

Danke

**Comment by Kruemelino** [comment]
[FBDBSetup_5.0.3.21_230207-0618.zip](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/files/10671732/FBDBSetup_5.0.3.21_230207-0618.zip)

Hier nochmal ein Test. Wenn der auch schief läuft, muss ich noch viel tiefer rein.

**Comment by atwcc** [comment]
Guten Morgen, leider noch immer mit Fehlermeldung.

**Comment by Kruemelino** [comment]
Ich habe das jetzt auf mehreren Rechnern getestet. Auf Keinem konnte ich das Problem nachstellen. Selbst die Testversionen, die das Ribbon nicht haben, zeigen eine Fehlermeldung. Daher vermute ich das Problem auf deinem Rechner liegt. Vielleicht schießt ein Virenscanner quer.

Sofern die funktionierende Version für dich ausreichend ist und es keine Fehler gibt, würde ich dazu raten, bei der Version zu bleiben.

**Comment by atwcc** [comment]
Vielen Dank für deine Bemühungen, ich werde die ältere Version weiterverwenden.
