### ISSUE TITLE
FR: Thunderbird "fork"

### ISSUE THREAD

**Issue by GitMensch** [Kruemelino/FritzBoxTelefon-dingsbums#66]
Erst einmal: Respekt, dass dieses Projekt so lange weiter geführt und modernisiert wurde - und noch immer mit dem Fritz!OS mitzieht.

Da aber nicht jeder ein Outlook (oder gar Windows, aber das wäre eine andere Sache) benutzt, hier die Frage nach einer Thunderbird-Variante.
Vor sehr langer Zeit gab es dazu mal Gedanken, aber gefunden habe ich dazu nix mehr.

Es gab vor noch längerer Zeit die fbdial-Erweiterung für Thunderbird, aber diese ist auch mit Thunderbird nicht mehr kompatibel (von der FB API ganz zu schweigen); hier im Code heißt der Hauptordner so - reiner Zufall?

Daher hier ein Frageliste:

* fbdb + Thunderbird:
     * Gab es für Thunderbird mal konkretere Ansätze?
* fbdb technisch
     * Könnte man den Outlook-Teil in komplett in eigenen Klassen legen (z. B. `Microsoft.Office.Interop` nur in der eigentlichen Implementation, Rest jeweils in einer abstrakten Basisklasse belassen)?
     * Ist bekannt, ob der Code mit Mono übersetzbar ist?
     * Gibt es evtl. "lokal" noch alte Tags? Auf Github wurden nur [4 (!) gepusht](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/tags), vielleicht ist ein `git push --tags` (ggf. nach "cleanup") möglich?

* Thunderbird:
     * Sind ähnliche Projekte mit Thunderbird bekannt - zumindest mit einem Teil des riesigen Funktionsumfanges?
     * ~~Ist bekannt, ob man die Klassen als DLL kompilieren und in einer Erweiterung für Thunderbird laden könnte?~~ Für Thunderbird Extensions braucht es Javascript für den Code (und WebExtensions für die Thunderbird-Kommunikation). Man kann daher keine DLLs laden, aber zumindest könnte man versuchen die Klassen durch einen Transpiler durchlaufen zu lassen; damit würde man sich den großen Teil der Kommunikation mit der Fritz!Box sparen. [Auch wenn es da nur "alte" Software zu geben scheint. Entweder VB.NET -> C# > Javascript (scriptsharp, netjs) oder VB.NET -> CIL -> Javascript (jsil).]
     * Gibt es Interessenten, die bei diesen Umständen ggf. mitentwickeln könnten?

**Comment by Kruemelino** [comment]
Hallo Simon,

schön von dir zu hören. 

Das andere Ticket #65 habe ich geschlossen, da ich den Link aktualisiert habe.

Nun zu diesem Thema:
Da das ganze Addin ist mit .NET geschrieben, da dies für die Integration in Outlook am einfachsten ist. Ein Großteil des Codes in diesem dient zur Integration in Outlook bzw. GUI (WPF). 

Die Kommunikation mit der Fritz!Box erfolgt über TR-064 und lua-Abfragen. Beides wird durch die [FBoxAPI](https://github.com/Kruemelino/FBoxAPI) realisiert (Name ist reiner Zufall). Momentan muss ich diese Schnittstelle aktualisieren, da AVM fast alle Dokumentationsdateien aktualisiert hat.

Mit Thunderbird bin ich nie warm geworden. Ich musste es mal nutzen, aber ich bin mittlerweile froh, dass ich nur noch Outlook (auch auf Arbeit) nutzen darf. Daher habe ich mich auch nie mit der Thematik im Zusammenhang mit Thunderbird beschäftigt.

Falls du für deine Zwecke etwas für die TR064-Schnittstelle der Fritz!Box findest, ist eigentlich alles möglich. Ich glaube nicht, dass man dieses Addin als Basis für eine Thunderbird-Version nutzen kann. Sicher kann man Ideen und Ansätze übernehmen. Auch der Wechsel zwischen vb.net zu c# ist mit viel Arbeit verbunden. Ich habe es mit automatischen Konvertern probiert. Der Code ist nicht schön und bedarf viel Optimierungen. Da kann man es auch neu schreiben. Diesen Aufwand wollte ich bis jetzt nicht betreiben.

Ich bin mit github nicht wirklich firm (Tags etc.). Ich nutze es eigentlich nur zur Bereitstellung des Codes. Mir fehlen einige Grundlagen bei der  Arbeit mit Github. 

Das Addin wird von wenigen Leuten genutzt. Wenn die Versionen 100 mal heruntergeladen werden ist es viel. 

VG

Gert

**Comment by GitMensch** [comment]
Die saubere Trennung in die FBoxAPI ist super, dann ist auch die primäre Integration in Outlook logisch (die Rückwärtssuche wäre wohl noch fast 1:1 zu übernehmen, aber sonst nix). Mit dem Rest hast du sicher Recht: Ideen zu übernehmen wäre sinnvoll - aber zuerst müsste man wohl die entsprechenden Teile der FBoxAPI erst mal nach Javascript portieren...

Damit sind die wichtigen Infos erst einmal zusammen und ein direkter fork ist einfach nicht möglich, daher mache ich dieses Ticket mal zu. Wenn jemand anders Interesse an der Arbeit hat - gerne hier posten, wenn 2 oder 3 zusammen daran arbeiten, dann könnte man ja mit dem reinen Anrufmonitor und/oder der Wählhilfe mal beginnen... sonst hebe ich mir das auf, bis ich mal tiefer in Javascript eintauchen möchte.

Dir @Kruemelino auch weiterhin Erfolg mit dem plug-in, 100 Nutzer sind nicht so wenig... sicher werden es mehr, wenn man jemanden bei Heise oder Chip auf das Plugin ansetzen könnte...

PS: Auf Arbeit muss ich Outlook nutzen und bin froh, dass ich lokal den Thunderbird habe ;-)
