### ISSUE TITLE
5.0.3.24 liest die DECT-Telefone nicht aus?

### ISSUE THREAD

**Issue by krheinwald** [Kruemelino/FritzBoxTelefon-dingsbums#70]
Habe gerade einen Rechner neu mit Windows 11, Outlook 2021 und FBTD 5.0.3.24 aufgesetzt.

Beim Einlesen der Telefone und Daten von der FB wird soweit alles eingelesen, nur die DECT-Telefone nicht.

Irgendeine Idee?

**Comment by Kruemelino** [comment]
Da müsstest du mir mal ein Log zusenden. Ich hatte was geändert. Bei mir hat es funktioniert.

**Comment by krheinwald** [comment]
Lag an BitDefneder, der die Abfrage der FB als gefährlich blockiert.
