### ISSUE TITLE
Fritz!Box 7360 funktioniert nicht

### ISSUE THREAD

**Issue by PrieserMax** [Kruemelino/FritzBoxTelefon-dingsbums#71]
Ich habe mir das Add-In installiert mit den entsprechenden Voraussetzungen.
Leider zieht es sich nichts von der Fritz!Box
![Fehler_Log_Prüfer](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/assets/96659068/b0385232-7c11-4cf0-8c5b-c6d8026d6ad8)
Beim Wählen kommt immer folgendes. Wenn ich manuell eine Nummer eingebe, kann ich auch nichts auswählen bei "Verbinden über..."
![Fehler2](https://github.com/Kruemelino/FritzBoxTelefon-dingsbums/assets/96659068/9f1ff535-d050-4955-bd2b-8e2adfb7b1f3)

Info: FritzBox 7360, OS 6.35
PC: Windows 11, Office 2021

Vielleicht ist die Fritz!Box ja nicht kompatibel.
Danke schon mal im voraus

Gruß
Max

**Comment by Kruemelino** [comment]
Hallo,

da musst du mir mal das Log zusenden. Es kann sein, dass die Firmware der Fritz!Box zu alt ist.

**Comment by PrieserMax** [comment]
Hallom

danke für die Antwort.

Habe spontan eine 7490 bekommen, damit geht es leider auch nicht.

Wo finde ich das Log denn?

Gruß
Max

**Comment by Kruemelino** [comment]
Im Pfad %AppData%\Roaming\Fritz!Box Telefon-Dingsbums
